name: mdbook

on:
  pull_request:

env:
  MDBOOK_VERSION: 0.4.21
  MDBOOK_ALERTS_VERSION: 0.6.7
  MDBOOK_LINKCHECK_VERSION: 0.7.7

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook@${{ env.MDBOOK_VERSION }}

      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook-alerts@${{ env.MDBOOK_ALERTS_VERSION }}

      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook-linkcheck@${{ env.MDBOOK_LINKCHECK_VERSION }}

      - name: Build with mdBook
        run: mdbook build component-model
